// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjzjhftmtgajmpfeiksk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqempoZnRtdGdham1wZmVpa3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzg2MTQsImV4cCI6MjA2MjQ1NDYxNH0.wL7rNWCvDypWBvU_df172otyXclo1wbqZTic081LVJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);